name: Build Project
run-name: Building Project
on: 
  push:
    branches:
      - master
      - develop
  pull_request:
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
           node-version: 16.19.x
      - name: Setup PostgreSQL With Init Scripts
        uses: m4nu56/postgresql-action@1.0
        with:
          # POSTGRES_DB - name for the default database that is created
          postgresql db: bdi
          # POSTGRES_USER - create the specified user with superuser power
          postgresql user: postgres
          # POSTGRES_PASSWORD - superuser password
          postgresql password: postgres
      - name: Install dependencies
        run: npm ci
      - name: Run Project
        run: npm run build
      - name: Test project
        run: npm test
